# Generated by Django 3.1.3 on 2021-07-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210626_0614'),
        ('employees', '0002_auto_20210629_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='services',
            field=models.ManyToManyField(blank=True, to='products.Product'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['user'], name='employees_e_user_id_a18cc6_idx'),
        ),
    ]
