# Generated by Django 3.1.3 on 2021-07-08 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0003_auto_20210702_1626'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0006_auto_20210708_0259'),
        ('products', '0006_product_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Spending'), (1, 'Recharge'), (2, 'Recharge and Spending')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pst', models.DecimalField(decimal_places=2, max_digits=2)),
                ('gst', models.DecimalField(decimal_places=2, max_digits=2)),
                ('checkout_snapshot', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.appointment')),
                ('checked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_checkout_set', to='employees.employee')),
                ('products', models.ManyToManyField(to='products.Product')),
                ('served_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='served_checkout_set', to='employees.employee')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='checkout',
            index=models.Index(fields=['user'], name='checkouts_c_user_id_f61fe2_idx'),
        ),
        migrations.AddIndex(
            model_name='checkout',
            index=models.Index(fields=['served_by'], name='checkouts_c_served__d6f769_idx'),
        ),
        migrations.AddIndex(
            model_name='checkout',
            index=models.Index(fields=['checked_by'], name='checkouts_c_checked_82ba8d_idx'),
        ),
        migrations.AddIndex(
            model_name='checkout',
            index=models.Index(fields=['created_at'], name='checkouts_c_created_1d1df2_idx'),
        ),
    ]
