# Generated by Django 3.1.3 on 2021-07-08 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
