# Generated by Django 3.1.3 on 2021-07-13 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_duration'),
        ('checkouts', '0002_checkout_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='products',
            field=models.ManyToManyField(blank=True, to='products.Product'),
        ),
    ]
