# Generated by Django 3.1.3 on 2021-07-13 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0003_auto_20210713_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
