# Generated by Django 3.1.3 on 2021-07-02 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=16)),
                ('last_name', models.CharField(max_length=16)),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')])),
                ('phone', models.CharField(max_length=14)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['user'], name='customers_c_user_id_c1d57c_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['balance'], name='customers_c_balance_44a805_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['gender', 'created_at'], name='customers_c_gender_a1432a_idx'),
        ),
    ]
