# Generated by Django 3.1.3 on 2021-07-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Not Given'), (1, 'Male'), (2, 'Female')], default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
