# Generated by Django 3.1.3 on 2021-07-06 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20210702_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tier',
            field=models.IntegerField(choices=[(0, 'Normal User'), (1, 'Tier 1'), (2, 'Tier 2'), (3, 'Tier 3')], default=0),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tier'], name='customers_c_tier_655e79_idx'),
        ),
    ]
