# Generated by Django 3.1.3 on 2021-07-08 02:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0003_auto_20210702_1626'),
        ('appointments', '0002_appointment_is_canceled'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('user', 'appointment_time'), ('staff', 'appointment_time')},
        ),
    ]
