# Generated by Django 3.1.3 on 2021-06-26 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20210624_2221'),
        ('products', '0002_auto_20210625_2257'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('category', 'name')},
        ),
    ]
