# Generated by Django 3.1.3 on 2021-06-26 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210626_0601'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_categor_cd4531_idx',
        ),
    ]
