# Generated by Django 3.1.3 on 2021-06-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210626_0602'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'name'], name='products_pr_categor_cd4531_idx'),
        ),
    ]
