# Generated by Django 3.1.3 on 2021-07-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210626_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='duration',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
